[package]
name = "vec"
version = "0.0.2"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]

[lib]
name = "vec"
path = "src/lib.rs"

[profile.dev]
opt-level = 3
debug = false

[profile.release]
opt-level = 3
debug = false

[profile.test]
opt-level = 3
debug = false

